import { ReactNode } from "react";
import type { Metadata } from "next";
import { InterFont } from "assets/font";
import "styles/globals.css";

export const metadata: Metadata = {
  title: "Emoji Todo",
  description: "Generated by create next app",
  icons: {
    icon: "/laugh-emoji.png",
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={InterFont.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
